name: My first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: welcom message
              run: echo "my first github action workflow"

            - name: list file
              run: ls
            - name: checkout
              uses: actions/checkout@v4
        
            - name: Read file
              run: cat README.md