name: My first workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
            - name: welcom message
              run: echo "my first github action workflow"

            - name: list file
              run: ls
            - name: checkout
              uses: actions/checkout@v4

            - name: updating the system
              run: sudo apt install cowsay -y

            - name: script testing
              run: cowsay -f dragon "run for your life i'm the dragon " >>dragon.txt

            - name: Uploading Artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon-test-file
                path: dragon.txt
    
    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: dragon-test-file
            
            
        - name: Read file
          run: cat dragon.txt